### ISSUE TITLE
Add bosskey

### ISSUE THREAD

**Issue by at15** [Chuibility/Xuan-Selected#1]
> Are you worry about be catched by your parents when you are playing games? Are you often catched by your parents when you are talking with girls or boys on QQ? You won't need to worry about that anymore! Our Bosskey is used to solve it!

https://sourceforge.net/projects/bosskey/

**Comment by JasonQSY** [comment]
👍 Surprised to see it still exists and can be found now.

**Comment by JasonQSY** [comment]
It has been already added into the repo.
